### ISSUE TITLE
adding a new reflector produces error (version 3.0 / plone 4.2.5)

### ISSUE THREAD

**Issue by faro76** [collective/Products.Reflecto#4]
Es ist leider ein Fehler aufgetreten…
Dies ist die vollständige Fehlermeldung:

Zeige Fehlerbericht als Text

Traceback (innermost last):

Module ZPublisher.Publish, line 60, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 46, in call_object
Module Products.CMFPlone.FactoryTool, line 438, in **call**
Module Products.CMFPlone.FactoryTool, line 202, in **getitem**
Module Products.CMFPlone.FactoryTool, line 68, in _createObjectByType
Module Products.CMFCore.TypesTool, line 552, in _constructInstance
Module Products.Reflecto.content.reflector, line 6, in addReflector
Module Products.Archetypes.BaseContent, line 43, in manage_afterAdd
Module Products.Archetypes.BaseObject, line 159, in manage_afterAdd
__traceback_info__: (<Reflector at /lpati/portal_factory/Reflector/reflector.2013-06-19.9871453040>, <Reflector at /lpati/portal_factory/Reflector/reflector.2013-06-19.9871453040>, <App.ProductContext.__FactoryDispatcher__ object at 0xbcc2450>)
Module Products.Archetypes.BaseObject, line 174, in initializeLayers
Module Products.Archetypes.BaseObject, line 817, in Schema
Module zope.component.hooks, line 104, in adapter_hook
Module archetypes.schemaextender.extender, line 140, in cachingInstanceSchemaFactory
Module zope.component.hooks, line 104, in adapter_hook
Module Products.Reflecto.uuids, line 17, in reflectoUUID
AttributeError: _at_uid

**Comment by davisagli** [comment]
Sorry about that. Fixed in version 3.0.1

**Comment by faro76** [comment]
wow, that was really quick. thanx a lot!!
